// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { mpe, mpeT } from './mpe';


export class mpecollection {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):mpecollection {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsmpecollection(bb:flatbuffers.ByteBuffer, obj?:mpecollection):mpecollection {
  return (obj || new mpecollection()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsmpecollection(bb:flatbuffers.ByteBuffer, obj?:mpecollection):mpecollection {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new mpecollection()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

RECORDS(index: number, obj?:mpe):mpe|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new mpe()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

RECORDSLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startmpecollection(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addRECORDS(builder:flatbuffers.Builder, RECORDSOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, RECORDSOffset, 0);
}

static createRECORDSVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRECORDSVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endmpecollection(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static creatempecollection(builder:flatbuffers.Builder, RECORDSOffset:flatbuffers.Offset):flatbuffers.Offset {
  mpecollection.startmpecollection(builder);
  mpecollection.addRECORDS(builder, RECORDSOffset);
  return mpecollection.endmpecollection(builder);
}

unpack(): mpecollectionT {
  return new mpecollectionT(
    this.bb!.createObjList(this.RECORDS.bind(this), this.RECORDSLength())
  );
}


unpackTo(_o: mpecollectionT): void {
  _o.RECORDS = this.bb!.createObjList(this.RECORDS.bind(this), this.RECORDSLength());
}
}

export class mpecollectionT {
constructor(
  public RECORDS: (mpeT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const RECORDS = mpecollection.createRECORDSVector(builder, builder.createObjectOffsetList(this.RECORDS));

  return mpecollection.creatempecollection(builder,
    RECORDS
  );
}
}
